FROM arm64v8/node:20-alpine

RUN apk add g++ make py3-pip
# libusb-dev libusb-1.0-dev
RUN apk add udev

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY test.js .

ARG PORT
ENV PORT=$PORT

EXPOSE $PORT

CMD ["node", "test.js"]